import java.lang.Exception;
public class twoExceptions {

    public static void main(String[] args) {
        try {
            int[] array = {-1, 2, 3};
            int result = array[-2] / 0; // Both exceptions will be thrown
        } catch (NegativeArraySizeException e) {
            System.out.println("NegativeArraySizeException caught: " + e.getMessage());
        } catch (ArithmeticException e) {
            System.out.println("ArithmeticException caught: " + e.getMessage());
        }
    }
}
